export const EVENTSUB_SESSTION_ID_STORAGE_KEY_0 = "eventsub_sessionid[0]" as const;

// export enum EEventSubEvents {
//   ChannelAdBreakBegin = "channel.ad_break.begin",
//   ChannelBan = "channel.ban",
//   ChannelChannelPointsCustomRewardAdd = "channel.channel_points_custom_reward.add",
//   ChannelChannelPointsCustomRewardRemove = "channel.channel_points_custom_reward.remove",
//   ChannelChannelPointsCustomRewardRedemptionAdd = "channel.channel_points_custom_reward_redemption.add",
//   ChannelChannelPointsCustomRewardRedemptionUpdate = "channel.channel_points_custom_reward_redemption.update",
//   ChannelCharityCampaignDonate = "channel.charity_campaign.donate",
//   ChannelCharityCampaignProgress = "channel.charity_campaign.progress",
//   ChannelCharityCampaignStart = "channel.charity_campaign.start",
//   ChannelCharityCampaignStop = "channel.charity_campaign.stop",
//   ChannelCheer = "channel.cheer",
//   ChannelFollow = "channel.follow",
//   ChannelGoalBegin = "channel.goal.begin",
//   ChannelGoalEnd = "channel.goal.end",
//   ChannelGoalProgress = "channel.goal.progress",
//   ChannelHypeTrainBegin = "channel.hype_train.begin",
//   ChannelHypeTrainEnd = "channel.hype_train.end",
//   ChannelHypeTrainProgress = "channel.hype_train.progress",
//   ChannelModeratorAdd = "channel.moderator.add",
//   ChannelModeratorRemove = "channel.moderator.remove",
//   ChannelPollBegin = "channel.poll.begin",
//   ChannelPollEnd = "channel.poll.end",
//   ChannelPollProgress = "channel.poll.progress",
//   ChannelPredictionBegin = "channel.prediction.begin",
//   ChannelPredictionEnd = "channel.prediction.end",
//   ChannelPredictionLock = "channel.prediction.lock",
//   ChannelPredictionProgress = "channel.prediction.progress",
//   ChannelRaid = "channel.raid",
//   ChannelShieldModeBegin = "channel.shield_mode.begin",
//   ChannelShieldModeEnd = "channel.shield_mode.end",
//   ChannelShoutoutCreate = "channel.shoutout.create",
//   ChannelShoutoutReceive = "channel.shoutout.receive",
//   ChannelSubscribe = "channel.subscribe",
//   ChannelSubscriptionEnd = "channel.subscription.end",
//   ChannelSubscriptionGift = "channel.subscription.gift",
//   ChannelSubscriptionMessage = "channel.subscription.message",
//   ChannelUnban = "channel.unban",
//   ChannelUnbanRequestCreate = "channel.unban_request.create",
//   ChannelUnbanRequestResolve = "channel.unban_request.resolve",
//   ChannelUpdate = "channel.update",
//   DropEntitlementGrant = "drop.entitlement.grant",
//   ExtensionBitsTransactionCreate = "extension.bits_transaction.create",
//   StreamOffline = "stream.offline",
//   StreamOnline = "stream.online",
//   UserAuthorizationGrant = "user.authorization.grant",
//   UserAuthorizationRevoke = "user.authorization.revoke",
//   UserUpdate = "user.update",
// }

export const EventSubEvents = {
  ChannelAdBreakBegin: "channel.ad_break.begin",
  ChannelBan: "channel.ban",
  ChannelChannelPointsCustomRewardAdd: "channel.channel_points_custom_reward.add",
  ChannelChannelPointsCustomRewardRemove: "channel.channel_points_custom_reward.remove",
  ChannelChannelPointsCustomRewardRedemptionAdd:
    "channel.channel_points_custom_reward_redemption.add",
  ChannelChannelPointsCustomRewardRedemptionUpdate:
    "channel.channel_points_custom_reward_redemption.update",
  ChannelCharityCampaignDonate: "channel.charity_campaign.donate",
  ChannelCharityCampaignProgress: "channel.charity_campaign.progress",
  ChannelCharityCampaignStart: "channel.charity_campaign.start",
  ChannelCharityCampaignStop: "channel.charity_campaign.stop",
  ChannelCheer: "channel.cheer",
  ChannelFollow: "channel.follow",
  ChannelGoalBegin: "channel.goal.begin",
  ChannelGoalEnd: "channel.goal.end",
  ChannelGoalProgress: "channel.goal.progress",
  ChannelHypeTrainBegin: "channel.hype_train.begin",
  ChannelHypeTrainEnd: "channel.hype_train.end",
  ChannelHypeTrainProgress: "channel.hype_train.progress",
  ChannelModeratorAdd: "channel.moderator.add",
  ChannelModeratorRemove: "channel.moderator.remove",
  ChannelPollBegin: "channel.poll.begin",
  ChannelPollEnd: "channel.poll.end",
  ChannelPollProgress: "channel.poll.progress",
  ChannelPredictionBegin: "channel.prediction.begin",
  ChannelPredictionEnd: "channel.prediction.end",
  ChannelPredictionLock: "channel.prediction.lock",
  ChannelPredictionProgress: "channel.prediction.progress",
  ChannelRaid: "channel.raid",
  ChannelShieldModeBegin: "channel.shield_mode.begin",
  ChannelShieldModeEnd: "channel.shield_mode.end",
  ChannelShoutoutCreate: "channel.shoutout.create",
  ChannelShoutoutReceive: "channel.shoutout.receive",
  ChannelSubscribe: "channel.subscribe",
  ChannelSubscriptionEnd: "channel.subscription.end",
  ChannelSubscriptionGift: "channel.subscription.gift",
  ChannelSubscriptionMessage: "channel.subscription.message",
  ChannelUnban: "channel.unban",
  ChannelUnbanRequestCreate: "channel.unban_request.create",
  ChannelUnbanRequestResolve: "channel.unban_request.resolve",
  ChannelUpdate: "channel.update",
  DropEntitlementGrant: "drop.entitlement.grant",
  ExtensionBitsTransactionCreate: "extension.bits_transaction.create",
  StreamOffline: "stream.offline",
  StreamOnline: "stream.online",
  UserAuthorizationGrant: "user.authorization.grant",
  UserAuthorizationRevoke: "user.authorization.revoke",
  UserUpdate: "user.update",
} as const;
